// vue-todo/src/components/TodoListItem.vue
<template>
  <div class="d-flex flex-row justify-content-around bd-highlight shadow-sm pt-2 rounded">
    <div class="input-group p-2 ml-2">
      <input type="text"  class="form-control text-danger"
        v-model="todoInput"
        @dblclick="doEdit"
        @keyup.enter="update"
        :readonly="!edit"
      >
    </div>
    <button type="button" class="close ml-auto" aria-label="Close" @click="removeTodo">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
</template>

<script>
export default {
  props: {
    todo: {
      type: Object,
      required: true
    }
  },
  data (vm) {
    return {
      todoInput: vm.todo.content,
      edit: false
    }
  },
  methods: {
    removeTodo () {
      this.$emit('removeTodo', this.todo.id)
    },
    doEdit () {
      this.edit = true
    },
    update () {
      this.$emit('update', {
        id: this.todo.id,
        content: this.todoInput
      })
      this.edit = false
    }
  }
}
</script>

<style scoped>

</style>

// react-todo/src/components/TodoListItem.js
import React, { Component } from 'react'

class TodoListItem extends Component {
  state = {
    todoInput: this.props.todo.content,
    edit: false
  }

  handleChange = (e) => {
    this.setState({
      todoInput: e.target.value
    })
  }

  handleEdit = () => {
    this.setState({edit: true})
  }

  handleKeyPress = (e) => {
    if (e.key === 'Enter') {
      let { todo, updateTodo } = this.props
      updateTodo({
        id: todo.id,
        content: this.state.todoInput
      })
      this.setState({edit: false})
    }
  }

  render () {
    let { deleteTodo, todo } = this.props
    return (
      <div className="d-flex flex-row justify-content-around bd-highlight shadow-sm pt-2 rounded">
        <div className="input-group p-2 ml-2">
          <input type="text"  className="form-control text-danger"
            value={this.state.todoInput}
            onChange={this.handleChange}
            readOnly={!this.state.edit}
            onDoubleClick={this.handleEdit}
            onKeyPress={this.handleKeyPress}
          />
        </div>
        <button type="button" className="close ml-auto" aria-label="Close" onClick={() => deleteTodo(todo.id)}>
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
    )
  }
}

export default TodoListItem
